// <auto-generated />
using System;
using GiaPha_Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GiaPha_Infrastructure.Migrations
{
    [DbContext(typeof(DbGiaPha))]
    [Migration("20260202070857_AddHoIdToNotification")]
    partial class AddHoIdToNotification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GiaPha_Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("SuKienId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TenAlbum")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("ThanhVienId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("longtext");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NewValues")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ChiHo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<Guid>("IdHo")
                        .HasColumnType("char(36)");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<string>("TenChiHo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("TruongChiId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IdHo");

                    b.HasIndex("TruongChiId");

                    b.ToTable("ChiHos");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("SuKienId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ThanhVienId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.Ho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<string>("TenHo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Hos");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.HonNhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<Guid>("ChongId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("NgayKetHon")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayLyHon")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoiKetHon")
                        .HasColumnType("longtext");

                    b.Property<Guid>("VoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChongId");

                    b.HasIndex("VoId");

                    b.ToTable("HonNhans");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<Guid?>("ChiHoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("HoId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("NguoiNhanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChiHoId");

                    b.HasIndex("HoId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.QuanHeChaCon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<Guid>("ChaMeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoaiQuanHe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChaMeId");

                    b.HasIndex("ConId");

                    b.ToTable("QuanHeChaCons");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.SuKien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("DiaDiem")
                        .HasColumnType("longtext");

                    b.Property<int>("LoaiSuKien")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayXayRa")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ThanhVienId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ThanhVienId");

                    b.ToTable("SuKiens");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.TaiKhoanNguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("ActivationCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ChiHoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauMaHoa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("ThanhVienId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChiHoId");

                    b.HasIndex("ThanhVienId")
                        .IsUnique();

                    b.ToTable("TaiKhoanNguoiDungs");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.TepTin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LoaiTep")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("SuKienId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ThanhVienId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ThanhVienId");

                    b.ToTable("TepTins");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ThanhTuu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<int?>("NamDatDuoc")
                        .HasColumnType("int");

                    b.Property<string>("TenThanhTuu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("ThanhVienId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ThanhVienId");

                    b.ToTable("ThanhTuu");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ThanhVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ChiHoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("DoiThu")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayMat")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoiMat")
                        .HasColumnType("longtext");

                    b.Property<string>("NoiSinh")
                        .HasColumnType("longtext");

                    b.Property<string>("TieuSu")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChiHoId");

                    b.ToTable("ThanhViens");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ChiHo", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.Ho", "Ho")
                        .WithMany("CacChiHo")
                        .HasForeignKey("IdHo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "TruongChi")
                        .WithMany()
                        .HasForeignKey("TruongChiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ho");

                    b.Navigation("TruongChi");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.HonNhan", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "Chong")
                        .WithMany()
                        .HasForeignKey("ChongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "Vo")
                        .WithMany()
                        .HasForeignKey("VoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chong");

                    b.Navigation("Vo");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.Notification", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ChiHo", "ChiHo")
                        .WithMany()
                        .HasForeignKey("ChiHoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GiaPha_Domain.Entities.Ho", "Ho")
                        .WithMany()
                        .HasForeignKey("HoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChiHo");

                    b.Navigation("Ho");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.QuanHeChaCon", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "ChaMe")
                        .WithMany()
                        .HasForeignKey("ChaMeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "Con")
                        .WithMany()
                        .HasForeignKey("ConId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChaMe");

                    b.Navigation("Con");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.SuKien", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "ThanhVien")
                        .WithMany()
                        .HasForeignKey("ThanhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.TaiKhoanNguoiDung", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ChiHo", "ChiHo")
                        .WithMany()
                        .HasForeignKey("ChiHoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "ThanhVien")
                        .WithOne()
                        .HasForeignKey("GiaPha_Domain.Entities.TaiKhoanNguoiDung", "ThanhVienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChiHo");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.TepTin", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.Album", null)
                        .WithMany("TepTins")
                        .HasForeignKey("ThanhVienId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ThanhTuu", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ThanhVien", "ThanhVien")
                        .WithMany()
                        .HasForeignKey("ThanhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ThanhVien", b =>
                {
                    b.HasOne("GiaPha_Domain.Entities.ChiHo", "ChiHo")
                        .WithMany("ThanhViens")
                        .HasForeignKey("ChiHoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChiHo");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.Album", b =>
                {
                    b.Navigation("TepTins");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.ChiHo", b =>
                {
                    b.Navigation("ThanhViens");
                });

            modelBuilder.Entity("GiaPha_Domain.Entities.Ho", b =>
                {
                    b.Navigation("CacChiHo");
                });
#pragma warning restore 612, 618
        }
    }
}
